### ISSUE TITLE
Update examples using Bootstrap 4.x to Bootstrap 5.x

### ISSUE THREAD

**Issue by liviucotfas** [liviucotfas/ase-multimedia#3]
Updates using Bootstrap 4 should be updated to Bootstrap 5.x

https://getbootstrap.com

**Comment by erkovacs** [comment]
@erkovacs Note to self: Example ./Labs/08. Audio/code-examples/speech-api doesn't seem to be working. Maybe the speech recognition API has changed since implementation. Also should remove JQuery dependence as it's bound to cause confusion.

**Comment by erkovacs** [comment]
Also review archives:

modified:   Labs/03. Graphics.2D - Raster/code-examples/canvas-processing-2/*
modified:   Labs/08. Audio/code-examples/audio-playlist/*
modified:   Labs/08. Audio/code-examples/audio-web-audio-api/*
modified:   Labs/08. Audio/code-examples/speech-api/*
modified:   Labs/09. Video/code-examples/video-effects/*
modified:   Labs/09. Video/code-examples/video-processing/*
